# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /
    defaults: { _controller: 'App\Controller\UserController::index' }

login:
    path: /login
    defaults:
        _controller: App\Controller\UserController::login

login_check:
    path: /login_check

logout:
    path: /logout
    controller: App\Controller\UserController::logout

signUp:
    path: /signUp
    controller: App\Controller\UserController::signUp

edit_profil:
    path: /profile/edit
    controller: App\Controller\UserController::edit

instruments:
    path: /shop/instruments
    controller: App\Controller\ShopController::instruments

add_instrument:
    path: /admin/instrument/add
    controller: App\Controller\ShopController::addInstrument

add_category:
    path: /admin/category/add
    controller: App\Controller\ShopController::addCategory

edit_instrument:
    path: /admin/instrument/edit/{id}
    requirements:
        id: '\d+'
    controller: App\Controller\ShopController::editInstrument

view_instruments:
    path: /admin/instrument/view
    controller: App\Controller\ShopController::viewInstrument

view:
    path: /view/{name}
    controller: App\Controller\ShopController::view

achat:
    path: /profile/buy/instrument/{id}
    requirements:
        id: '\d+'
    controller: App\Controller\BasketController::buy

panier:
    path: /profile/basket
    controller: App\Controller\BasketController::viewBasket

commande_valide:
    path: /profile/commande
    controller: App\Controller\BasketController::commande

reception:
    path: /profile/reception
    controller: App\Controller\BasketController::reception