# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /
    defaults: { _controller: 'App\Controller\UserController::index' }

login:
    path: /login
    defaults:
        _controller: App\Controller\UserController::login

login_check:
    path: /login_check

logout:
    path: /logout
    controller: App\Controller\UserController::logout

signUp:
    path: /signUp
    controller: App\Controller\UserController::signUp

edit_profil:
    path: /profile/edit
    controller: App\Controller\UserController::edit

instruments:
    path: /shop/instruments
    controller: App\Controller\ShopController::instruments

partitions:
    path: /shop/sheets
    controller: App\Controller\ShopController::sheets

add_instrument:
    path: /admin/instrument/add
    controller: App\Controller\ShopController::addInstrument

add_partition:
    path: /admin/sheet/add
    controller: App\Controller\ShopController::addSheet

edit_instrument:
    path: /admin/partition/edit
    controller: App\Controller\ShopController::editInstrument

edit_partition:
    path: /admin/sheet/edit/{id}
    requirements:
        id: '\d+'
    controller: App\Controller\ShopController::editSheet

view_instruments:
    path: /admin/instrument/view
    controller: App\Controller\ShopController::viewInstrument

view_partitions:
    path: /admin/sheet/view
    controller: App\Controller\ShopController::viewSheet